version = 0.1
[default.deploy.parameters]
stack_name = "sam-kandidat-2030s"
resolve_s3 = true
s3_prefix = "sam-kandidat-2030"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "MyBucketName=\"kandidat-2030s\""
image_repositories = []
